### PR TITLE
removes filename prefixes

### PR DESCRIPTION
**Pull request by crashingbooth**
Sorry! As it turns out, MiniTidal doesn't return anything for `n "-1"` (whereas vanilla Tidal returns the last sample in the dir) - so while the samples with the prefixes did start at note 60, notes 12-59, were effectively hidden.  This PR removes any attempt at cleverness

### CODE REVIEW

**Comment by dktr0** [comment]
Why don't I fix that behaviour in WebDirt instead?

**Comment by crashingbooth** [comment]
If that is a straightforward fix, then that would be ideal! Being able to use negative values there would be helpful.  Otherwise, I can make do using `n ("0 -1" +48)`, which works in MiniTidal (assuming the samples have no prefixes).

**Comment by dktr0** [comment]
Okay - in the currently deployed Estuary negative numbers for n count backwards through the sample bank. Maybe withdraw this pull request if that addresses it successfully?

**Comment by crashingbooth** [comment]
awesome thanks! just tried it and it works great.  Closing the PR . . .

**Pull request closed without merging**
